apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: community-node
resources:
- services/geth-service.yaml
- services/prysm-service.yaml
- statefulsets/geth-statefulset.yaml
- statefulsets/prysm-statefulset.yaml
- volumes/geth-chaindata.yaml
- volumes/prysm-chaindata.yaml
configMapGenerator:
  - name: geth-jwt
    files: ["jwt.hex"]
    options:
      disableNameSuffixHash: true
images:
  - name: ethereum/client-go
    newTag: stable
  - name: gcr.io/prysmaticlabs/prysm/beacon-chain
    newTag: latest