apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prysm
  namespace: community-node
spec:
  selector:
    matchLabels:
      app: prysm
  serviceName: prysm
  template:
    metadata:
      labels:
        app: prysm
    spec:
      containers:
        - name: beacon
          image: gcr.io/prysmaticlabs/prysm/beacon-chain
          args:
            - --accept-terms-of-use
            - --datadir=/data/dir
            - --disable-monitoring
            - --rpc-host=0.0.0.0
            - --execution-endpoint=http://geth-service.community-node.svc.cluster.local:8551
            - --jwt-secret=/gethjwt/jwt.hex
            - --rpc-host=0.0.0.0
            - --rpc-port=4000
            - --grpc-gateway-corsdomain=*
            - --grpc-gateway-host=0.0.0.0
            - --grpc-gateway-port=3500
            - --checkpoint-sync-url=http://testing.mainnet.beacon-api.nimbus.team/
            - --genesis-beacon-api-url=http://testing.mainnet.beacon-api.nimbus.team/
          ports:
            - containerPort: 4000
              name: grpc
            - containerPort: 3500
              name: jsonrpc
            - containerPort: 13000
              name: p2ptcp
            - containerPort: 12000
              protocol: UDP
              name: p2pudp
          readinessProbe:
            tcpSocket:
              port: 4000
          livenessProbe:
            tcpSocket:
              port: 4000
          startupProbe:
            failureThreshold: 60
            tcpSocket:
              port: 4000
            periodSeconds: 60
          resources:
            limits:
              cpu: 8000m
              memory: 8G
            requests:
              cpu: 1000m
              memory: 4G
          volumeMounts:
            - mountPath: /data
              name: chaindata
            - mountPath: /gethjwt
              name: gethjwt
      volumes:
        - name: chaindata
          persistentVolumeClaim:
            claimName: prysm-chaindata
        - configMap:
            name: geth-jwt
          name: gethjwt
