apiVersion: v1
kind: PersistentVolume
metadata: 
  name: prysm-chaindata
  namespace: community-node
spec:
  storageClassName: prysm-chaindata
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/mnt/prysm-chaindata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prysm-chaindata
  namespace: community-node
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prysm-chaindata
  resources:
    limits:
      storage: 1000Gi 
    requests: 
      storage: 1000Gi 